M48
; DRILL file {KiCad 8.0.2-8.0.2-0~ubuntu23.10.1} date 2024-05-30T16:45:30+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-30T16:45:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-8.0.2-0~ubuntu23.10.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X10.75Y-6.0
X13.29Y-6.0
T2
X3.0Y-25.175
X12.0Y-9.175
X21.0Y-25.175
M30
